---
- name: Copy the new logrotate configuration
  template:
    src: logrotate.j2
    dest: "/etc/logrotate.d/{{ item.name }}"
    owner: root
    group: root
    mode: 0644
    backup: true
  tags:
    - logrotate-setup

- name: Ensure the logrotate configuration is valid
  command: "logrotate -d /etc/logrotate.d/{{ item.name }}"
  register: config_file_stat
  changed_when: false
  ignore_errors: true
  tags:
    - logrotate-setup

- name: Ensure backup files will be removed
  find:
    paths: /etc/logrotate.d/
    patterns: "{{ item.name }}.*"
  register: files_to_delete
  when: config_file_stat is not failed
  tags:
    - logrotate-setup

- name: Ensure backup files are removed
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  when:
    - config_file_stat is not failed
    - files_to_delete is defined
  tags:
    - logrotate-setup

- name: Retrieve the name of the old logrotate config if the new one is invalid
  shell: "ls -tr1 /etc/logrotate.d/{{ item.name }}.* | tail -1"
  register: latest_backup
  ignore_errors: true
  when: config_file_stat is failed
  tags:
    - logrotate-setup

- name: Restore the latest logrotate valid configuration
  command: "mv {{ latest_backup.stdout }} /etc/logrotate.d/{{ item.name }}"
  when: config_file_stat is failed
  tags:
    - logrotate-setup

- name: Fail if the new logrotate configuration is invalid
  fail:
    msg: Logrotate check has failed due an invalid configuration
  when: config_file_stat is failed
  tags:
    - logrotate-setup
